App/fuzzyapp/fuzzyapp/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from fuzzyapp import views


urlpatterns = patterns('',
    url(r'^$', views.ListaMateriasView.as_view(), name='lista-materias'),
    url(r'^agrupar$', views.AgruparMateriasView.as_view(), name='lista-materias'),
)

App/fuzzyapp/fuzzyapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

"""
Este módulo provee algo parecido a un ORM sobre los objetos que nos
interesa representar en la base de datos difusa.

Se implementa haciendo uso de la capa de abstracción implementada en el
módulo fuzzyapp.database.

Estos NO son modelos de Django, es nuestra propia implementación de un
ORM. Sin embargo, está bastante inspirado en el API del ORM de Django,
de esta forma es más fácil de entender.
"""

from fuzzyapp.database import fuzzyQuery, fuzzyStatement


class MateriaQuerySet(object):
    """
    Obtiene de forma perezosa objetos Materia desde la base de datos.

    Inicialmente representa una consulta que no se ha ejecutado,
    la cual puede refinarse con los métodos filter() y order_by().

    Al iniciar el iterador, se ejecuta la consulta y se instancian
    objetos Materia utilizando el resultado.
    """

    def __init__(self):
        self.conditions = []
        self.order_columns = []

    def filter(self, **kwargs):
        """
        Agrega una condición para filtrar las materias en la base de datos
        Cada argumento que se le pase representa una condición.
        Actualmente soporta las siguientes condiciones:

        * <columna>__startswithany = <valores>: busca aquellos elementos cuya
            columna <columna> comience por algún string en <valores>
        * <columna>__exact = <valor>: aquellos elementos cuya columna <columna>
            sea exactamente igual a <valor>
        """
        for key, value in kwargs.items():
            # Va a explotar si pasna algo como a__b__c
            # Esto no es Django, a lo sumo soportamos algo como
            # <columna>__<operador>.
            column, operator = key.rsplit("__")
            if operator == "startswithany":
                condition_format = "(" + column + " LIKE '{value}%')"
                conditions = map(
                    lambda x: condition_format.format(value=x),
                    value
                )
                self.conditions.append("(" + " OR ".join(conditions) + ")")
            elif operator == "exact":
                self.conditions.append("({column} = '{value}')".format(
                    column=column,
                    value=value
                ))
            else:
                raise NotImplementedError(
                    "Can't filter using operator {op}".format(op=operator)
                )
        return self

    def id_unidad_in(self, ids):
        """
        Método para filtrar por aquellas materias que se relacionen con una unidad
        con id en 'ids'. Lo pongo aquí cara e tabla porque ya estoy harto de este
        proyecto y quiero salir del paso.
        """
        condition_format = "(ua.id_unidad = {value})"
        conditions = map(
            lambda x: condition_format.format(value=x),
            ids
        )
        self.conditions.append("(" + " OR ".join(conditions) + ")")

    def order_by(self, column, direction='DESC'):
        """
        Recibe una secuencia de columnas sobre las cuales ordenar el resultado.
        """
        self.order_columns += ((column, direction), )
        return self

    def _get_sql_query(self):
        """
        Construye la sentencia SQL necesaria para buscar todos los elementos
        que hacen match con las condiciones actuales de este QuerySet.
        """
        ################# TODO ##################
        # Esta es la consulta base para pedir materias
        # Estoy asumiendo la existencia de una tabla 'asignatura_fuzzy'
        # con las columnas para los difusos, el booleano 'stale' y
        # el codigo de la materia para poder hacerle join con asingatura.
        # También estoy asumiendo que todas las tablas están en un
        # schema llamado 'opinion'.
        # Hay que cambiarlo para que se ajuste a la realidad, si hace falta.
        sql = (
            "SELECT DISTINCT a.codigo, a.nombre, af.stale, af.calificacion, af.preparacion, af.dificultad "
            "FROM opinion.asignatura as a "
            "JOIN opinion.asignatura_fuzzy as af USING (codigo) "
            "LEFT OUTER JOIN opinion.unidad_asignatura as ua USING (codigo) "
        )
        ################# TODO #################

        # Agregar condiciones WHERE, si las hay
        if len(self.conditions) > 0:
            sql += " WHERE "
            sql += " AND ".join(self.conditions)

        # Agregar ORDER BY, si hace falta
        if len(self.order_columns) > 0:
            sql += " ORDER BY "
            sql += ','.join(map(lambda (col, dir): col + " " + dir, self.order_columns))

        ############# TODO ############
        # Aquí hay que crear el diccionario que se le pasa a fuzzyQuery
        # para decirle qué columnas debe extraer del resultado de la
        # consulta y cómo convertirlas a Python.
        # Entonces hay que ajustar esto a los nombres reales de las
        # columnas o que se yo. Hay que probar a ver que pasa.

        query_columns = {
            "codigo": {"type": "string"},
            "nombre": {"type": "string"},

            "stale": {"type": "boolean"},
            "calificacion": {"type": "fuzzy", "subtype_converter": int},
            "preparacion": {"type": "fuzzy", "subtype_converter": int},
            "dificultad": {"type": "fuzzy", "subtype_converter": int}
        }
        ########### TODO ##############3

        return sql, query_columns

    def __iter__(self):
        """
        Devuelve un generador que ejecuta la consulta del QuerySet y
        genera las instancias de Materia correspondientes al resultado.
        """
        sql, query_columns = self._get_sql_query()
        for row in fuzzyQuery(sql, query_columns):
            ############ TODO ############
            # Aquí hay que extraer los valores de row e instanciar
            # una Materia con ellos.
            # Luego de instanciar hay que ver si es necesario actualizar
            # los valores difusos. Si es necesario, entonces hacen las
            # consultas necesarias para calcularlo, instancian los
            # nuevos FuzzyExtension, se los asignan a los campos
            # correspondientes de la instancia de Materia, y hacen
            # .save() sobre la Materia.
            # Por ahora dejo instanciarlo sin argumentos para poder
            # ir probando otras cosas.

            # TODO: Instanciar Materia
            materia = Materia(
                codigo=row["codigo"],
                nombre=row["nombre"],
                calificacion=row["calificacion"],
                preparacion=row["preparacion"],
                dificultad=row["dificultad"],
            )
            materia._update_on_save = True

            # TODO: Chequear que los atributos fuzzy no estén stale.
            # (ese flag debería estar en el row)

            # TODO: Recalcular atrivutos difusos, si hace falta
            # TODO: Guardar los nuevos atributos difusos, si hace falta

            ############ TODO ############
            yield materia


class MateriaManager(object):
    """
    Permite obtener un MateriaQuerySet inicial con el cual comenzar
    a refinar una consulta.
    """

    def all(self):
        """
        Devuelve un QuerySet que hace match con todas las Materias en la
        base de datos.
        """
        return MateriaQuerySet()

    def get(self, **kwargs):
        """
        Devuelve un QuerySet de todas las Materias, filtrado según los
        kwargs que se le pasen.
        """
        return MateriaQuerySet().filter(**kwargs)


class Materia(object):
    """
    Representa un objeto de tipo Materia con todos sus campos.

    Puede instanciarse directamente para luego insertar nuevos objetos
    de este tipo en base de datos, o pueden ser generados por
    MateriaQuerySet para representar objetos existentes.

    Campos:
    codigo -- string
    nombre -- string
    calificacion -- un FuzzyExtension (la clase en database.py)
    preparacion -- un FuzzyExtension
    dificultad -- un FuzzyExtension

    FIXME: Otros campos que sean útiles?
    """

    objects = MateriaManager()

    def __init__(self, codigo, nombre, calificacion, preparacion, dificultad):
        ########## TODO ##########
        # Acomodar si hace falta

        self.codigo = codigo  # Clave primaria
        self.nombre = nombre
        self.calificacion = calificacion
        self.preparacion = preparacion
        self.dificultad = dificultad
        self._update_on_save = False

        ########### TODO #########

    def save(self):
        """
        Actualiza en base de datos los registros correspondientes a este
        objeto. Si no existe, se crea uno nuevo.
        """
        ############### TODO #############
        # Implementar esto
        # La idea es generar las consultas
        if self._update_on_save:
            pass
            # Hacer consultas UPDATE en vez de INSERT
        else:
            pass
            # Hacer consultas INSERT
            # Marcar esta instancia _update_on_save = True, pues luego
            # de un INSERT el próximo save() tiene que ser un update.
            # Realmente no creo que vayamos a usar esto, pero lo pongo
            # por completitud del API.
        ################ TODO ############

App/fuzzyapp/fuzzyapp/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from fuzzyapp.database import fuzzyQuery


campos_ordenamiento = (
    ('', "---"),
    ('calificacion', "Calificación esperada"),
    ('preparacion', "Preparación previa"),
    ('dificultad', "Dificultad del curso")
)


direccion = (
    ('ASC', "Ascendente"),
    ('DESC', "Descendente")
)


def filtros_dptos():
    query = "SELECT id_unidad, nombre FROM opinion.unidad WHERE mostrar = 'Y'"
    columns = {
        "id_unidad": {"type": "integer"},
        "nombre": {"type": "string"}
    }
    result = []
    for row in fuzzyQuery(query, columns):
        result.append((row['id_unidad'], row['nombre']))
    return result


class FiltroMateriasForm(forms.Form):
    """
    Formulario para filtrar y ordenar las materias de opinión estudiantil.
    Permite elegir cuáles departamentos mostrar (basado en sus códigos)
    y hasta 3 campos sobre los cuales ordenar el resultado.
    """
    filtrar_dptos = forms.BooleanField(initial=False, required=False, label="¿Filtrar unidades?")
    dptos = forms.MultipleChoiceField(choices=filtros_dptos(), required=False, label="Unidades")
    orden1 = forms.ChoiceField(choices=campos_ordenamiento, required=False, label="Primer campo para ordenar")
    asc1 = forms.ChoiceField(choices=direccion, required=False, initial='DESC', label="Dirección")
    orden2 = forms.ChoiceField(choices=campos_ordenamiento, required=False, label="Segundo campo para ordenar")
    asc2 = forms.ChoiceField(choices=direccion, required=False, initial='DESC', label="Dirección")
    orden3 = forms.ChoiceField(choices=campos_ordenamiento, required=False, label="Tercer campo para ordenar")
    asc3 = forms.ChoiceField(choices=direccion, required=False, initial='DESC', label="Dirección")


class AgruparMateriasForm(forms.Form):
    campo = forms.ChoiceField(choices=campos_ordenamiento)

App/fuzzyapp/fuzzyapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import View
from django.shortcuts import render_to_response

from fuzzyapp.database import fuzzyQuery, convert_fuzzy
from fuzzyapp.models import Materia
from fuzzyapp.forms import FiltroMateriasForm, AgruparMateriasForm


class ListaMateriasView(View):

    def get(self, request):
        # Por default lista todas las materias y muestra un formulario
        # para filtrarlas y ordenarlas.
        materias = Materia.objects.all()
        form = FiltroMateriasForm()
        return render_to_response(
            "fuzzyapp/lista_materias.html",
            {"materias": list(materias), "form": form}
        )

    def post(self, request):
        # Filtra y ordena las materias si el formulario era válido
        # sino, por default hace los mismo que GET
        form = FiltroMateriasForm(request.POST)
        materias = Materia.objects.all()
        if form.is_valid():
            if form.cleaned_data["filtrar_dptos"]:
                materias.id_unidad_in(form.cleaned_data["dptos"])
            orden1 = form.cleaned_data["orden1"]
            orden2 = form.cleaned_data["orden2"]
            orden3 = form.cleaned_data["orden3"]
            if orden1 != '':
                materias.order_by(orden1, direction=form.cleaned_data["asc1"])
            if orden2 != '':
                materias.order_by(orden2, direction=form.cleaned_data["asc2"])
            if orden3 != '':
                materias.order_by(orden3, direction=form.cleaned_data["asc3"])

        return render_to_response(
            "fuzzyapp/lista_materias.html",
            {"materias": list(materias), "form": form}
        )


c = {
    "calificacion": "Calificación",
    "preparacion": "Preparación",
    "dificultad": "Dificultad"
}


class AgruparMateriasView(View):
    """
    En este view no estoy usando nuestro models, sino que uso directamente fuzzyQuery.
    La razón es que no hay manera fácil de integrar la funcionalidad de agregación a
    nuestro miniframework de materias, así que es más fácil hacerlo a mano.
    """

    def get(self, request):
        resultado = []
        form = AgruparMateriasForm()
        return render_to_response(
            "fuzzyapp/agrupar_materias.html",
            {"resultado": resultado, "form": form}
        )

    def post(self, request):
        form = AgruparMateriasForm(request.POST)
        resultado = []
        if form.is_valid():
            campo = form.cleaned_data["campo"]
            if campo == '':
                return render_to_response(
                    "fuzzyapp/agrupar_materias.html",
                    {"resultado": resultado, "form": form}
                )
            query = (
                "SELECT array_agg(a.codigo) as codigos, array_agg(a.nombre) as nombres, array_agg(af.{campo}) as campos "
                "FROM opinion.asignatura as a "
                "JOIN opinion.asignatura_fuzzy as af USING(codigo) "
                "GROUP BY af.{campo} "
            )

            query = query.format(campo=campo)
            columns = {
                "codigos": {"type": "array", "subtype_converter": unicode},
                "nombres": {"type": "array", "subtype_converter": unicode},
                "campos": {"type": "array", "subtype_converter": lambda x: convert_fuzzy(x.toString(), int)}
            }
            resultado = list(fuzzyQuery(query, columns))
            resultado = list(map(lambda x: zip(x['codigos'], x['nombres'], x['campos']), resultado))

        return render_to_response(
            "fuzzyapp/agrupar_materias.html",
            {"resultado": resultado, "form": form, "campo": c[campo]}
        )

App/fuzzyapp/fuzzyapp/templates/fuzzyapp/agrupar_materias.html
{% load addcss %}
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="http://getbootstrap.com/assets/ico/favicon.ico">

    <title>Atributos difusos tipo 2 - Ene-Mar 2014</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="/static/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="/static/jquery-1.11.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

    <style>
    body {
      padding-top: 50px;
    }
    .starter-template {
      /*padding: 40px 15px;*/
    }
    .lol {
        width: 50%;
    }
    #id_filtrar_dptos {
        width: auto;
    }
    </style>


    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">MPDS Ene-Mar 2014</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Listar / Ordenar</a></li>
            <li class="active"><a href="/agrupar">Agrupar</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="starter-template">



<h2>Materias con atributos difusos</h2>

<h3>Agrupar de acuerdo a una columna difusa</h3>

<form action="/agrupar" method="post">
            {% for field in form %}
              <div class="form-group">
                <label>{{ field.label }}</label>
                {{field | addcss:"form-control lol"}}
              </div>
            {% endfor %}
        <input type="submit" value="Buscar" class="btn btn-default" />
</form>

<hr />

<table class='table table-striped'>
    <thead>
        <tr>
            <th>Código</th>
            <th>Materia</th>
            <th>{{ campo }}</th>
        </tr>
    </thead>
    <tbody>
        {% for materias in resultado %}
            {% for materia in materias %}
                <tr>
                    <td>{{ materia.0 }}</td>
                    <td>{{ materia.1 }}</td>
                    <td>{{ materia.2 }}</td>
                </tr>
            {% endfor %}
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
        {% endfor %}
    </tbody>
</table>

      </div>

    </div><!-- /.container -->

</body></html>

App/fuzzyapp/fuzzyapp/templates/fuzzyapp/lista_materias.html
{% load addcss %}
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="http://getbootstrap.com/assets/ico/favicon.ico">

    <title>Atributos difusos tipo 2 - Ene-Mar 2014</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="/static/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="/static/jquery-1.11.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

    <style>
    body {
      padding-top: 50px;
    }
    .starter-template {
      /*padding: 40px 15px;*/
    }
    .lol {
        width: 50%;
    }
    #id_filtrar_dptos {
        width: auto;
    }
    </style>


    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">MPDS Ene-Mar 2014</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Listar / Ordenar</a></li>
            <li><a href="/agrupar">Agrupar</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="starter-template">

        <h2>Materias con atributos difusos</h2>

        <h3>Ordenar de acuerdo a una columna difusa</h3>

        <form action="/" method="post" class="form">
            {% for field in form %}
              <div class="form-group">
                <label>{{ field.label }}</label>
                {{field | addcss:"form-control lol"}}
              </div>
            {% endfor %}
        <input type="submit" value="Buscar" class="btn btn-default" />
        </form>

        <hr />

        <table class='table table-striped'>
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Nombre</th>
                    <th>Calificación esperada</th>
                    <th>Dificultad</th>
                    <th>Preparación previa</th>
                </tr>
            </thead>
            <tbody>
                {% for materia in materias %}
                <tr>
                    <td>{{ materia.codigo }}</td>
                    <td>{{ materia.nombre }}</td>
                    <td>{{ materia.calificacion }}</td>
                    <td>{{ materia.dificultad }}</td>
                    <td>{{ materia.preparacion }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td>No hay materias para mostrar.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
      </div>

    </div><!-- /.container -->

</body></html>